on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  update-asset:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Generate ogp images
        run: deno task ogp
        working-directory: ./deno
     
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: blog-cdn
          directory: ./asset
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
