on:
  repository_dispatch:
    types: [newt-webhook]
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  update-asset:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Generate ogp images
        env: 
          NEWT_SPACE_UID: ${{ secrets.NEWT_SPACE_UID }}
          NEWT_API_TOKEN: ${{ secrets.NEWT_API_TOKEN }}
          NEWT_API_TYPE: ${{ secrets.NEWT_API_TYPE }}
          NEWT_APP_UID: ${{ secrets.NEWT_APP_UID }}
          NEWT_POST_MODEL_UID: ${{ secrets.NEWT_POST_MODEL_UID }}
          NEWT_TAG_MODEL_UID: ${{ secrets.NEWT_TAG_MODEL_UID }}
        run: |
          deno task setup:chrome
          deno task ogp
        working-directory: ./deno
     
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: blog-cdn
          directory: ./asset
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
